# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181007_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectstripeaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConnectStripeAccount',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
