# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181015_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_requires_18',
            field=models.BooleanField(default=False),
        ),
    ]
