# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('like', models.BooleanField(default=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=255, null=True)),
                ('content', models.ManyToManyField(to='content.Content')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='ParentComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
