# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20181029_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
