# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_sub', models.BooleanField(default=False)),
                ('re_subbed', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('points_add', models.BooleanField(default=False)),
                ('points_spent', models.BooleanField(default=False)),
                ('transactions', models.BooleanField(default=False)),
                ('tip', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
