# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notfication',
            name='user',
        ),
    ]
