# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0003_notfication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfication',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
